import { JobApplication, JobStatus, WorkType, EmploymentType } from '../types/job';

/**
 * 50 Trustable Job Applications for Siftly Mock Mode.
 * Covers diverse sectors, statuses, and currencies to stress-test the dashboard.
 */
export const MOCK_APPLICATIONS: JobApplication[] = [
  // --- Applied (15) ---
  {
    id: 'm1',
    company: 'Stripe',
    sector: 'Fintech',
    position: 'Product Designer',
    country: 'IE',
    city: 'Dublin',
    workType: 'remote',
    employmentType: 'permanent',
    status: 'applied',
    salary: { amount: 85000, currency: 'EUR' },
    date: '2024-03-25',
    links: { job: '#', linkedin: '#', website: 'https://stripe.com' },
    description: 'Design the future of online payments.',
  },
  {
    id: 'm2',
    company: 'Klarna',
    sector: 'Fintech',
    position: 'Backend Engineer (Go)',
    country: 'SE',
    city: 'Stockholm',
    workType: 'hybrid',
    employmentType: 'permanent',
    status: 'applied',
    salary: { amount: 750000, currency: 'SEK' },
    date: '2024-03-24',
    links: { job: '#', linkedin: '#', website: 'https://klarna.com' },
  },
  {
    id: 'm3',
    company: 'Revolut',
    sector: 'Fintech',
    position: 'Security Engineer',
    country: 'UK',
    city: 'London',
    workType: 'onsite',
    employmentType: 'permanent',
    status: 'applied',
    salary: { amount: 95000, currency: 'GBP' },
    date: '2024-03-23',
    links: { job: '#', linkedin: '#', website: 'https://revolut.com' },
  },
  {
    id: 'm4',
    company: 'Adyen',
    sector: 'Fintech',
    position: 'Fullstack Developer',
    country: 'NL',
    city: 'Amsterdam',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 82000, currency: 'EUR' },
    date: '2024-03-22',
    links: { job: '#', linkedin: '#', website: 'https://adyen.com' },
  },
  {
    id: 'm5',
    company: 'Wise',
    sector: 'Fintech',
    position: 'iOS Developer',
    country: 'EE',
    city: 'Tallinn',
    workType: 'remote',
    status: 'applied',
    salary: { amount: 65000, currency: 'EUR' },
    date: '2024-03-21',
    links: { job: '#', linkedin: '#', website: 'https://wise.com' },
  },
  {
    id: 'm6',
    company: 'Northvolt',
    sector: 'Green Tech',
    position: 'Battery Systems Engineer',
    country: 'SE',
    city: 'Skellefteå',
    workType: 'onsite',
    status: 'applied',
    salary: { amount: 680000, currency: 'SEK' },
    date: '2024-03-20',
    links: { job: '#', linkedin: '#', website: 'https://northvolt.com' },
  },
  {
    id: 'm7',
    company: 'Einride',
    sector: 'Autonomous',
    position: 'Robotics Engineer',
    country: 'SE',
    city: 'Stockholm',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 720000, currency: 'SEK' },
    date: '2024-03-19',
    links: { job: '#', linkedin: '#', website: 'https://einride.tech' },
  },
  {
    id: 'm8',
    company: 'Volvo Cars',
    sector: 'Automotive',
    position: 'Embedded Software Engineer',
    country: 'SE',
    city: 'Gothenburg',
    workType: 'onsite',
    status: 'applied',
    salary: { amount: 650000, currency: 'SEK' },
    date: '2024-03-18',
    links: { job: '#', linkedin: '#', website: 'https://volvocars.com' },
  },
  {
    id: 'm9',
    company: 'Ericsson',
    sector: 'Telecom',
    position: '5G Systems Architect',
    country: 'SE',
    city: 'Stockholm',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 800000, currency: 'SEK' },
    date: '2024-03-17',
    links: { job: '#', linkedin: '#', website: 'https://ericsson.com' },
  },
  {
    id: 'm10',
    company: 'H&M Group',
    sector: 'Retail',
    position: 'Data Scientist',
    country: 'SE',
    city: 'Stockholm',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 700000, currency: 'SEK' },
    date: '2024-03-16',
    links: { job: '#', linkedin: '#', website: 'https://hmgroup.com' },
  },
  {
    id: 'm11',
    company: 'Spotify',
    sector: 'Entertainment',
    position: 'Engineering Manager',
    country: 'US',
    city: 'New York',
    workType: 'remote',
    status: 'applied',
    salary: { amount: 245000, currency: 'USD' },
    date: '2024-03-15',
    links: { job: '#', linkedin: '#', website: 'https://spotify.com' },
  },
  {
    id: 'm12',
    company: 'Netflix',
    sector: 'Entertainment',
    position: 'Senior UI Engineer',
    country: 'US',
    city: 'Los Gatos',
    workType: 'remote',
    status: 'applied',
    salary: { amount: 350000, currency: 'USD' },
    date: '2024-03-14',
    links: { job: '#', linkedin: '#', website: 'https://netflix.com' },
  },
  {
    id: 'm13',
    company: 'Airbnb',
    sector: 'Travel',
    position: 'Infra Engineer',
    country: 'US',
    city: 'San Francisco',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 220000, currency: 'USD' },
    date: '2024-03-13',
    links: { job: '#', linkedin: '#', website: 'https://airbnb.com' },
  },
  {
    id: 'm14',
    company: 'DoorDash',
    sector: 'Logistics',
    position: 'Backend Developer',
    country: 'US',
    city: 'Seattle',
    workType: 'remote',
    status: 'applied',
    salary: { amount: 195000, currency: 'USD' },
    date: '2024-03-12',
    links: { job: '#', linkedin: '#', website: 'https://doordash.com' },
  },
  {
    id: 'm15',
    company: 'Instacart',
    sector: 'Logistics',
    position: 'Machine Learning Lead',
    country: 'CA',
    city: 'Toronto',
    workType: 'hybrid',
    status: 'applied',
    salary: { amount: 180000, currency: 'USD' },
    date: '2024-03-11',
    links: { job: '#', linkedin: '#', website: 'https://instacart.com' },
  },

  // --- Interviewing (10) ---
  {
    id: 'm16',
    company: 'Google',
    sector: 'Big Tech',
    position: 'Solution Architect',
    country: 'IT',
    city: 'Milan',
    workType: 'hybrid',
    status: 'interviewing',
    salary: { amount: 95000, currency: 'EUR' },
    date: '2024-02-28',
    links: { job: '#', linkedin: '#', website: 'https://google.com' },
    interviews: 2,
    rounds: [
      { id: 'r1', roundNumber: 1, date: '2024-03-10T10:00:00Z', interviewerName: 'Mario Rossi' },
      { id: 'r2', roundNumber: 2, date: '2024-03-20T15:00:00Z', interviewerName: 'Alice White' },
    ],
  },
  {
    id: 'm17',
    company: 'Amazon Web Services',
    sector: 'Big Tech',
    position: 'Cloud Engineer',
    country: 'IE',
    city: 'Dublin',
    workType: 'onsite',
    status: 'interviewing',
    salary: { amount: 110000, currency: 'EUR' },
    date: '2024-03-01',
    links: { job: '#', linkedin: '#', website: 'https://amazon.jobs' },
    interviews: 1,
  },
  {
    id: 'm18',
    company: 'Microsoft',
    sector: 'Big Tech',
    position: 'Azure Specialist',
    country: 'FR',
    city: 'Paris',
    workType: 'hybrid',
    status: 'interviewing',
    salary: { amount: 105000, currency: 'EUR' },
    date: '2024-03-05',
    links: { job: '#', linkedin: '#', website: 'https://microsoft.com' },
  },
  {
    id: 'm19',
    company: 'Meta',
    sector: 'Big Tech',
    position: 'React Core Contributor',
    country: 'US',
    city: 'Menlo Park',
    workType: 'remote',
    status: 'interviewing',
    salary: { amount: 450000, currency: 'USD' },
    date: '2024-03-08',
    links: { job: '#', linkedin: '#', website: 'https://meta.com' },
    phoneScreens: 1,
  },
  {
    id: 'm20',
    company: 'OpenAI',
    sector: 'Artificial Intelligence',
    position: 'LLM Fine-tuner',
    country: 'US',
    city: 'San Francisco',
    workType: 'onsite',
    status: 'interviewing',
    salary: { amount: 550000, currency: 'USD' },
    date: '2024-03-10',
    links: { job: '#', linkedin: '#', website: 'https://openai.com' },
  },
  {
    id: 'm21',
    company: 'Anthropic',
    sector: 'Artificial Intelligence',
    position: 'Safety Research Lead',
    country: 'US',
    city: 'San Francisco',
    workType: 'hybrid',
    status: 'interviewing',
    salary: { amount: 480000, currency: 'USD' },
    date: '2024-03-12',
    links: { job: '#', linkedin: '#', website: 'https://anthropic.com' },
  },
  {
    id: 'm22',
    company: 'Datadog',
    sector: 'SaaS',
    position: 'Reliability Engineer',
    country: 'DE',
    city: 'Berlin',
    workType: 'remote',
    status: 'interviewing',
    salary: { amount: 130000, currency: 'EUR' },
    date: '2024-03-14',
    links: { job: '#', linkedin: '#', website: 'https://datadog.com' },
  },
  {
    id: 'm23',
    company: 'Snowflake',
    sector: 'Data',
    position: 'Warehouse Architect',
    country: 'NL',
    city: 'Utrecht',
    workType: 'hybrid',
    status: 'interviewing',
    salary: { amount: 145000, currency: 'EUR' },
    date: '2024-03-16',
    links: { job: '#', linkedin: '#', website: 'https://snowflake.com' },
  },
  {
    id: 'm24',
    company: 'Palantir',
    sector: 'Data',
    position: 'Forward Deployed Engineer',
    country: 'CH',
    city: 'Zurich',
    workType: 'onsite',
    status: 'interviewing',
    salary: { amount: 185000, currency: 'EUR' },
    date: '2024-03-18',
    links: { job: '#', linkedin: '#', website: 'https://palantir.com' },
  },
  {
    id: 'm25',
    company: 'HashiCorp',
    sector: 'Infrastructure',
    position: 'Terraform Engineer',
    country: 'FR',
    city: 'Lyon',
    workType: 'hybrid',
    status: 'interviewing',
    salary: { amount: 120000, currency: 'EUR' },
    date: '2024-03-20',
    links: { job: '#', linkedin: '#', website: 'https://hashicorp.com' },
  },

  // --- Offers (5) ---
  {
    id: 'm26',
    company: 'Tesla',
    sector: 'Automotive',
    position: 'Autopilot Dev',
    country: 'US',
    city: 'Austin',
    workType: 'onsite',
    status: 'offer',
    salary: { amount: 280000, currency: 'USD' },
    date: '2024-02-15',
    links: { job: '#', linkedin: '#', website: 'https://tesla.com' },
  },
  {
    id: 'm27',
    company: 'Rivian',
    sector: 'Automotive',
    position: 'Battery Management Lead',
    country: 'US',
    city: 'Irvine',
    workType: 'hybrid',
    status: 'offer',
    salary: { amount: 250000, currency: 'USD' },
    date: '2024-02-18',
    links: { job: '#', linkedin: '#', website: 'https://rivian.com' },
  },
  {
    id: 'm28',
    company: 'Reddit',
    sector: 'Social Media',
    position: 'Algorithm Scientist',
    country: 'CA',
    city: 'Vancouver',
    workType: 'remote',
    status: 'offer',
    salary: { amount: 190000, currency: 'USD' },
    date: '2024-02-20',
    links: { job: '#', linkedin: '#', website: 'https://reddit.com' },
  },
  {
    id: 'm29',
    company: 'Twitch',
    sector: 'Entertainment',
    position: 'Stream Infrastructure',
    country: 'US',
    city: 'San Francisco',
    workType: 'hybrid',
    status: 'offer',
    salary: { amount: 210000, currency: 'USD' },
    date: '2024-02-22',
    links: { job: '#', linkedin: '#', website: 'https://twitch.tv' },
  },
  {
    id: 'm30',
    company: 'Discord',
    sector: 'Social Media',
    position: 'Voice Quality Lead',
    country: 'NL',
    city: 'Amsterdam',
    workType: 'remote',
    status: 'offer',
    salary: { amount: 160000, currency: 'EUR' },
    date: '2024-02-25',
    links: { job: '#', linkedin: '#', website: 'https://discord.com' },
  },

  // --- Rejected (10) ---
  {
    id: 'm31',
    company: 'Twitter / X',
    sector: 'Social Media',
    position: 'Everything App Specialist',
    country: 'US',
    status: 'rejected',
    salary: { amount: 0, currency: 'USD' },
    date: '2024-01-10',
    city: 'San Francisco',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://x.com' },
  },
  {
    id: 'm32',
    company: 'Uber',
    sector: 'Logistics',
    position: 'Payment Architect',
    country: 'NL',
    status: 'rejected',
    salary: { amount: 140000, currency: 'EUR' },
    date: '2024-01-15',
    city: 'Amsterdam',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://uber.com' },
  },
  {
    id: 'm33',
    company: 'Lyft',
    sector: 'Logistics',
    position: 'Driver Experience',
    country: 'CA',
    status: 'rejected',
    salary: { amount: 170000, currency: 'USD' },
    date: '2024-01-20',
    city: 'Montreal',
    workType: 'remote',
    links: { job: '#', linkedin: '#', website: 'https://lyft.com' },
  },
  {
    id: 'm34',
    company: 'Snap',
    sector: 'Social Media',
    position: 'AR Specialist',
    country: 'US',
    status: 'rejected',
    salary: { amount: 200000, currency: 'USD' },
    date: '2024-01-25',
    city: 'Santa Monica',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://snapchat.com' },
  },
  {
    id: 'm35',
    company: 'Intel',
    sector: 'Hardware',
    position: 'Chip Designer',
    country: 'IL',
    status: 'rejected',
    salary: { amount: 120000, currency: 'USD' },
    date: '2024-01-30',
    city: 'Haifa',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://intel.com' },
  },
  {
    id: 'm36',
    company: 'NVIDIA',
    sector: 'Hardware',
    position: 'CUDA Optimizer',
    country: 'US',
    status: 'rejected',
    salary: { amount: 300000, currency: 'USD' },
    date: '2024-02-05',
    city: 'Santa Clara',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://nvidia.com' },
  },
  {
    id: 'm37',
    company: 'AMD',
    sector: 'Hardware',
    position: 'GPU Architect',
    country: 'CA',
    status: 'rejected',
    salary: { amount: 220000, currency: 'USD' },
    date: '2024-02-10',
    city: 'Toronto',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://amd.com' },
  },
  {
    id: 'm38',
    company: 'Salesforce',
    sector: 'SaaS',
    position: 'Cloud Manager',
    country: 'US',
    status: 'rejected',
    salary: { amount: 240000, currency: 'USD' },
    date: '2024-02-15',
    city: 'Indianapolis',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://salesforce.com' },
  },
  {
    id: 'm39',
    company: 'Oracle',
    sector: 'Big Tech',
    position: 'DBA Lead',
    country: 'US',
    status: 'rejected',
    salary: { amount: 230000, currency: 'USD' },
    date: '2024-02-20',
    city: 'Austin',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://oracle.com' },
  },
  {
    id: 'm40',
    company: 'IBM',
    sector: 'Big Tech',
    position: 'Quantum Researcher',
    country: 'US',
    status: 'rejected',
    salary: { amount: 260000, currency: 'USD' },
    date: '2024-02-25',
    city: 'Yorktown Heights',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://ibm.com' },
  },

  // --- No-Response (10) ---
  {
    id: 'm41',
    company: 'Tencent',
    sector: 'Entertainment',
    position: 'Gaming Consultant',
    country: 'CN',
    status: 'no-response',
    salary: { amount: 1000000, currency: 'USD' },
    date: '2023-11-01',
    city: 'Shenzhen',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://tencent.com' },
  },
  {
    id: 'm42',
    company: 'Alibaba',
    sector: 'E-commerce',
    position: 'Logistics Lead',
    country: 'CN',
    status: 'no-response',
    salary: { amount: 850000, currency: 'USD' },
    date: '2023-11-05',
    city: 'Hangzhou',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://alibaba.com' },
  },
  {
    id: 'm43',
    company: 'Booking.com',
    sector: 'Travel',
    position: 'Senior Developer',
    country: 'NL',
    status: 'no-response',
    salary: { amount: 95000, currency: 'EUR' },
    date: '2023-11-10',
    city: 'Amsterdam',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://booking.com' },
  },
  {
    id: 'm44',
    company: 'Skyscanner',
    sector: 'Travel',
    position: 'Flights Architect',
    country: 'UK',
    status: 'no-response',
    salary: { amount: 90000, currency: 'GBP' },
    date: '2023-11-15',
    city: 'Edinburgh',
    workType: 'remote',
    links: { job: '#', linkedin: '#', website: 'https://skyscanner.net' },
  },
  {
    id: 'm45',
    company: 'Tripadvisor',
    sector: 'Travel',
    position: 'Review Auditor',
    country: 'US',
    status: 'no-response',
    salary: { amount: 155000, currency: 'USD' },
    date: '2023-11-20',
    city: 'Needham',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://tripadvisor.com' },
  },
  {
    id: 'm46',
    company: 'Cisco',
    sector: 'Networking',
    position: 'Packet Sniffer Specialist',
    country: 'US',
    status: 'no-response',
    salary: { amount: 185000, currency: 'USD' },
    date: '2023-11-25',
    city: 'San Jose',
    workType: 'hybrid',
    links: { job: '#', linkedin: '#', website: 'https://cisco.com' },
  },
  {
    id: 'm47',
    company: 'VMware',
    sector: 'Virtualization',
    position: 'Kernel Dev',
    country: 'US',
    status: 'no-response',
    salary: { amount: 195000, currency: 'USD' },
    date: '2023-12-01',
    city: 'Palo Alto',
    workType: 'remote',
    links: { job: '#', linkedin: '#', website: 'https://vmware.com' },
  },
  {
    id: 'm48',
    company: 'Red Hat',
    sector: 'Open Source',
    position: 'Kernel Architect',
    country: 'DE',
    status: 'no-response',
    salary: { amount: 115000, currency: 'EUR' },
    date: '2023-12-05',
    city: 'Munich',
    workType: 'onsite',
    links: { job: '#', linkedin: '#', website: 'https://redhat.com' },
  },
  {
    id: 'm49',
    company: 'GitLab',
    sector: 'DevOps',
    position: 'Sidekiq Specialist',
    country: 'US',
    status: 'no-response',
    salary: { amount: 175000, currency: 'USD' },
    date: '2023-12-10',
    city: 'Remote',
    workType: 'remote',
    links: { job: '#', linkedin: '#', website: 'https://gitlab.com' },
  },
  {
    id: 'm50',
    company: 'GitHub',
    sector: 'DevOps',
    position: 'Actions Lead Developer',
    country: 'US',
    status: 'no-response',
    salary: { amount: 185000, currency: 'USD' },
    date: '2023-12-15',
    city: 'Remote',
    workType: 'remote',
    links: { job: '#', linkedin: '#', website: 'https://github.com' },
  },
];
